/**
 * Generated by tsnapi — public API snapshot of `dts-snapshot-repro`
 */
// #region Interfaces
export interface ImageModelOptions<TComponent = unknown> {
  node: ImageRenderNode;
  imageOptions?: ImageOptions<TComponent>;
  fallbackAttempted?: boolean;
  imageLoaded?: boolean;
  isHardenUrl?: boolean;
  loadError?: boolean;
}
export interface ImageOptions<TComponent = unknown> {
  fallback?: string;
  caption?: boolean;
  component?: TComponent;
}
export interface ImageRenderNode {
  url: string;
  alt?: string | null;
  title?: string | null;
  loading?: boolean;
}
// #endregion

// #region Functions
export declare function createImageModel<TComponent = unknown>(_: ImageModelOptions<TComponent>): {
  readonly isLoading: boolean;
  readonly fallback: string;
  readonly imageSrc: string;
  readonly alt: string;
  readonly title: string;
  readonly showCaption: boolean;
  readonly figureWidth: "100%" | "auto";
  readonly showSpin: boolean;
  readonly showImage: boolean;
  readonly showError: boolean;
  readonly errorVariant: "harden-image" | "image";
};
// #endregion